<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>UnityEngine.UI</AssemblyName>
    <RootNamespace>UnityEngine.UI</RootNamespace>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Version>1.0.0</Version>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../UnityEngine.CoreModule/UnityEngine.CoreModule.csproj" />
    <ProjectReference Include="../UnityEngine.UIModule/UnityEngine.UIModule.csproj" />
  </ItemGroup>
</Project>
